[project]
name = "api1"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi[full]>=0.122.0",
    "uvicorn>=0.38.0",
]
